apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-argocd-deployment
spec:
  selector:
    matchLabels:
      app: myapp-argocd
  revisionHistoryLimit: 1  #field in a Deployment to specify how many old ReplicaSets for this Deployment you want to retain. The rest will be garbage-collected in the background. By default, it is 10.
  template:
    metadata:
      labels:
        app: myapp-argocd
    spec:
      containers:
        - name: myapp-argocd
          image: picher/argocd-demo:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
            limits:
              cpu: 900m
